export const eventBanking = {
  bank: "FNB",
  accountType: "Business account",
  account: "63135151221",
};
export const defaultSettings = {
  headline: "A little love. A stronger Krugersdorp.",
  intro:
    "Neighbours, businesses and communities coming together to make our town a place where everyone can thrive.",
  phone: "+27 82 829 9003",
  email: "",
  membershipPrice: 240,
  bankName: "FNB Business account",
  bankAccount: "63135151221",
  bankReference: "SLK",
  donationIntro: "Help turn compassion into practical support for our community.",
};
export const initialEntities = [
  {
    id: "event-network",
    kind: "events",
    title: "Business network gathering",
    category: "Business & networking",
    description:
      "Connect with people who care about growing local business and making a difference in Krugersdorp. The next date and venue will be announced here.",
    image: "/breakfast-cover.jpg",
    location: "Krugersdorp",
    date: "",
    time: "",
    status: "draft",
    capacity: 80,
    price: 0,
  },
  {
    id: "event-outreach",
    kind: "events",
    title: "Love in action",
    category: "Community & outreach",
    description:
      "Be part of our next community outreach. Register your interest to lend a hand, share your skills or contribute supplies.",
    image: "/community/outreach.jpg",
    location: "Krugersdorp",
    date: "",
    time: "",
    status: "draft",
    capacity: 150,
    price: 0,
  },
  {
    id: "event-faith",
    kind: "events",
    title: "United in faith",
    category: "Faith & fellowship",
    description:
      "Join a community rooted in faith, prayer and a shared commitment to our town. Register your interest for the next gathering.",
    image: "/community/gathering.jpg",
    location: "Krugersdorp",
    date: "",
    time: "",
    status: "draft",
    capacity: 300,
    price: 0,
  },
  {
    id: "voucher-example",
    kind: "vouchers",
    title: "Your next local favourite",
    category: "Community",
    description:
      "This is a demonstration voucher. The admin can replace it with an approved offer from a participating local business.",
    image: "/breakfast-cover.jpg",
    business: "Sample local business",
    benefit: "20% off",
    terms:
      "Demonstration only. No monetary value. One claim per member. Not valid at a real business.",
    expires: "2027-12-31",
    status: "draft",
    demo: true,
    limit: 100,
  },
  {
    id: "business-diestal",
    kind: "businesses",
    title: "Die Stal Ministry",
    category: "Ministry & wellbeing",
    description: "A space for healing, personal growth and equine-assisted support.",
    phone: "+27 82 829 9003",
    email: "diestalministry@gmail.com",
    website: "",
    location: "Krugersdorp",
    status: "published",
    ownerId: "",
    publicContact: true,
  },
  {
    id: "business-philadelphia",
    kind: "businesses",
    title: "Philadelphia Community Project",
    category: "Community & skills",
    description:
      "Handmade gift cards, skills development and opportunities for women in our community.",
    phone: "+27 72 323 4300",
    email: "debbiegiftcards@gmail.com",
    website: "",
    location: "Burgershoop, Krugersdorp",
    status: "published",
    ownerId: "",
    publicContact: true,
  },
];
